bot-token = ""

[instance1]
cmd-exec-dir = "" # has to be a full path
cmd-path = "" # absolut path or command available on the command line
cmd-args = [ "", "", "" ]
[instance1.startup]
time-to-wait = 10 # time to wait after command execution, or stdout finish
wait-for-stdout = true # if true waits for the stdout to finish befor counting the time
[instance1.restrictions]
server-id = 0
fallback-channel-id = 0
allowed-channel-ids = [ 0, 1 ] # todo: not used currently
allowed-user-ids = [ 0, 1 ] # todo: not used currently
[instance1.slash-commands]
start = { description = ""}
restart = { description = ""} # todo: not yet reserved, but will be soon
# custom slash commands
# writes to stdin and response with custom message ({} => instance-name)
stop = { description = "", stdin = { cmd = "stop", interaction-msg ="Stopping `{}`" } }
